version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
git config --global commit.gpgsign true
version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
